### ISSUE TITLE
Format README

### ISSUE THREAD

**Issue by doltonfernandes** [doltonfernandes/C_shell#1]

**Comment by psymbio** [comment]
Can I resolve this issue?

**Comment by psymbio** [comment]
also if you don't mind, code that's not placed inside a folder triggers my OCD in a way. If you place all your code in a folder the repository shall look better.

Good job on the code:) I solved the issue, just merge the pull request.

**Comment by doltonfernandes** [comment]
Done in 1a7cb793238b5c220d6bb62471e1f192a2a5d12c
